# Generated by Django 4.0.4 on 2022-10-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.publication', verbose_name='Пост'),
        ),
    ]
