# Generated by Django 4.0.4 on 2022-10-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_building_profile_number_profile_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.building', verbose_name='Корпус'),
        ),
    ]
